# Generated by Django 4.1 on 2022-08-22 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteration",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="isAnalyze",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="isCompleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="isDevelopment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="isTest",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="effortitem", unique_together={("task_item", "member")},
        ),
    ]
