# Generated by Django 4.1 on 2022-08-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_iteration_user_taskitem_isanalyze_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='task',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.taskitem'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance', to='api.taskitem'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
